stages:
  ani500k_small_CC:
    cmd: zntrack run mace_models.LoadModel --name ani500k_small_CC
    deps:
    - data/ani500k_small_CC.model
    metrics:
    - nodes/ani500k_small_CC/node-meta.json:
        cache: false
  ani500k_small_DFT:
    cmd: zntrack run mace_models.LoadModel --name ani500k_small_DFT
    deps:
    - data/ani500k_small_DFT.model
    metrics:
    - nodes/ani500k_small_DFT/node-meta.json:
        cache: false
  hydromace:
    cmd: zntrack run mace_models.LoadModel --name hydromace
    deps:
    - data/qm9_and_spice_hydrogenation.model
    metrics:
    - nodes/hydromace/node-meta.json:
        cache: false
  reference_data:
    cmd: zntrack run mace_models.XYZReader --name reference_data
    deps:
    - data/qm9_reference_data.xyz
    metrics:
    - nodes/reference_data/node-meta.json:
        cache: false
