stages:
  mace_model:
    cmd: zntrack run mace_models.LoadModel --name mace_model
    deps:
    - data/SPICE_Mini_for_Gen_swa.model
    metrics:
    - nodes/mace_model/node-meta.json:
        cache: false
  hydromace:
    cmd: zntrack run mace_models.LoadModel --name hydromace
    deps:
    - data/qm9_and_spice_hydrogenation.model
    metrics:
    - nodes/hydromace/node-meta.json:
        cache: false
  reference_data:
    cmd: zntrack run mace_models.XYZReader --name reference_data
    deps:
    - data/qm9_reference_data.xyz
    metrics:
    - nodes/reference_data/node-meta.json:
        cache: false
  linker_examples:
    cmd: zntrack run mace_models.XYZReader --name linker_examples
    deps:
    - data/zinc_fragments_difflinker.xyz
    metrics:
    - nodes/linker_examples/node-meta.json:
        cache: false
