MACE-MP-0:
  info: "\n        You're using the MACE-MP-0 model. The model is released under the\
    \ MIT license.\n        Note:\n        If you are using this model, please cite\
    \ the relevant paper for the Materials Project,\n        any paper associated\
    \ with the MACE model, and also the following:\n        - MACE-Universal by Yuan\
    \ Chiang, 2023, Hugging Face, Revision e5ebd9b,\n            DOI: 10.57967/hf/1202,\
    \ URL: https://huggingface.co/cyrusyc/mace-universal\n        - Matbench Discovery\
    \ by Janosh Riebesell, Rhys EA Goodall, Philipp Benner, Yuan Chiang,\n       \
    \     Alpha A Lee, Anubhav Jain, Kristin A Persson, 2023, arXiv:2308.14920\n \
    \       - https://arxiv.org/abs/2401.00096\n           "
MACE-MP-0_large:
  info: "\n        You're using the MACE-MP-0_large model. The model is released under\
    \ the MIT license.\n        Note:\n        If you are using this model, please\
    \ cite the relevant paper for the Materials Project,\n        any paper associated\
    \ with the MACE model, and also the following:\n        - MACE-Universal by Yuan\
    \ Chiang, 2023, Hugging Face, Revision e5ebd9b,\n            DOI: 10.57967/hf/1202,\
    \ URL: https://huggingface.co/cyrusyc/mace-universal\n        - Matbench Discovery\
    \ by Janosh Riebesell, Rhys EA Goodall, Philipp Benner, Yuan Chiang,\n       \
    \     Alpha A Lee, Anubhav Jain, Kristin A Persson, 2023, arXiv:2308.14920\n \
    \       - https://arxiv.org/abs/2401.00096\n           "
MACE-MP-0_small:
  info: "\n        You're using the MACE-MP-0_small model. The model is released under\
    \ the MIT license.\n        Note:\n        If you are using this model, please\
    \ cite the relevant paper for the Materials Project,\n        any paper associated\
    \ with the MACE model, and also the following:\n        - MACE-Universal by Yuan\
    \ Chiang, 2023, Hugging Face, Revision e5ebd9b,\n            DOI: 10.57967/hf/1202,\
    \ URL: https://huggingface.co/cyrusyc/mace-universal\n        - Matbench Discovery\
    \ by Janosh Riebesell, Rhys EA Goodall, Philipp Benner, Yuan Chiang,\n       \
    \     Alpha A Lee, Anubhav Jain, Kristin A Persson, 2023, arXiv:2308.14920\n \
    \       - https://arxiv.org/abs/2401.00096\n           "
ani500k_small:
  info: "\n        You're using the ani500k_small MACE model. The model is released\
    \ under the MIT license.\n        Note:\n        If you are using this function,\
    \ please cite the relevant paper associated with the MACE model, ANI dataset,\
    \ and also the following:\n        - \"Evaluation of the MACE Force Field Architecture\
    \ by D\xE1vid P\xE9ter Kov\xE1cs, Ilyes Batatia, Eszter S\xE1ra Arany, and G\xE1\
    bor Cs\xE1nyi, The Journal of Chemical Physics, 2023, URL: https://doi.org/10.1063/5.0155322\n\
    \            "
hydromace:
  info: "\n        You're using the hydromace model. The model is released under the\
    \ MIT license.\n        "
linker_examples:
  info: You're using data from the DiffLinker paper. Please cite https://doi.org/10.48550/arXiv.2210.05274
simgen_reference_data_medium:
  info: 'You''re using QM9 data. Please cite the QM9 dataset paper. URL: https://doi.org/10.1038/sdata.2014.22'
simgen_reference_data_small:
  info: 'You''re using QM9 data. Please cite the QM9 dataset paper. URL: https://doi.org/10.1038/sdata.2014.22'
