[tool.poetry]
name = "mace-models"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "mace_models"}]

[tool.poetry.dependencies]
python = "^3.10"
zntrack = {git = "https://github.com/zincware/ZnTrack.git"}
dvc-s3 = "^2.23.0"
ase = "^3.22.1"
torch = {version = "^1.13.0", source="torch"}
mace = {git = "https://github.com/RokasEl/mace.git", rev="extract-embeddings"}
hydromace = {git="https://github.com/RokasEl/hydromace.git"}
zndraw = "0.2.0a4"


[[tool.poetry.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cu116"
secondary = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
